### ISSUE TITLE
Valor de bônus default por departamento

### ISSUE THREAD

**Issue by stinow** [stinow/gioavaliacao#31]
Na pág de definir metas deve haver um campo que recebe o valor default da configuração_KPI, que pode ser alterado para o depto selecionado.
Na pág de metas funcionário, deve haver mais um campo contendo o valor do bônus do depto, que pode ser alterado especificamente para o funcionário também.

**Comment by EclesioMeloJunior** [comment]
Valor de bônus para um funcionário especifico finalizado com a criação de uma tabela para guardar esses registros de funcionário - valor.  Commit **cd0a479460ee08939e5b9d833034731c615466c0**
