### ISSUE TITLE
Permitir a exclusão de um questionário liberado

### ISSUE THREAD

**Issue by EclesioMeloJunior** [stinow/gioavaliacao#9]
Caso for preciso, um questionário liberado poderá ser excluído, retirando todos os vínculos existentes pra ele.

**Comment by stinow** [comment]
Alteração .1
- Ao invés de excluir, o avaliador poderá reverter o questionário. Ou seja: remover todos os vínculos da tabela questionario_funcionario e alterar o valor na coluna finalizado para 0, além de ser notificado sobre os vínculos que serão removidos. A partir daí ele poderá editar ou remover o questionário, se necessário.
